### ISSUE TITLE
demod blocks fail

### ISSUE THREAD

**Issue by ghost** [Agrim9/FHSS_GNUradio#1]
Ubuntu 16.04 64-bit, GNU Radio Companion 3.7.9

When creating a demod block, an error message is given. For demod_64:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/ActionHandler.py", line 348, in _handle_action
    self.get_flow_graph().update()
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/FlowGraph.py", line 403, in update
    self.create_labels()
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Element.py", line 78, in create_labels
    for child in self.get_children():child.create_labels()
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Block.py", line 212, in create_labels
    markups = [param.get_markup() for param in self.get_params() if param.get_hide() not in ('all', 'part')]
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/python/Param.py", line 170, in get_hide
    lambda p: ' '.join([p._type, p._nports]), self.get_parent().get_ports())
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/python/Param.py", line 170, in <lambda>
    lambda p: ' '.join([p._type, p._nports]), self.get_parent().get_ports())
TypeError: sequence item 0: expected string, instance found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/DrawingArea.py", line 150, in _handle_window_expose
    self._flow_graph.draw(gc, self._pixmap)
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/FlowGraph.py", line 372, in draw
    element.draw(gc, window)
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Block.py", line 318, in draw
    window.draw_drawable(gc, self.horizontal_label, 0, 0, x+BLOCK_LABEL_PADDING, y+(self.H-self.label_height)/2, -1, -1)
AttributeError: 'Block' object has no attribute 'horizontal_label'`

For demod_8:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/ActionHandler.py", line 348, in _handle_action
    self.get_flow_graph().update()
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/FlowGraph.py", line 403, in update
    self.create_labels()
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Element.py", line 78, in create_labels
    for child in self.get_children():child.create_labels()
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Block.py", line 212, in create_labels
    markups = [param.get_markup() for param in self.get_params() if param.get_hide() not in ('all', 'part')]
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/python/Param.py", line 170, in get_hide
    lambda p: ' '.join([p._type, p._nports]), self.get_parent().get_ports())
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/python/Param.py", line 170, in <lambda>
    lambda p: ' '.join([p._type, p._nports]), self.get_parent().get_ports())
TypeError: sequence item 0: expected string, instance found
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/DrawingArea.py", line 150, in _handle_window_expose
    self._flow_graph.draw(gc, self._pixmap)
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/FlowGraph.py", line 372, in draw
    element.draw(gc, window)
  File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Block.py", line 318, in draw
    window.draw_drawable(gc, self.horizontal_label, 0, 0, x+BLOCK_LABEL_PADDING, y+(self.H-self.label_height)/2, -1, -1)
AttributeError: 'Block' object has no attribute 'horizontal_label'`

EOF

**Comment by nttwtkw** [comment]
I have same problem :( 
Can you fix it ?

**Comment by nttwtkw** [comment]
> Ubuntu 16.04 64-bit, GNU Radio Companion 3.7.9
> 
> When creating a demod block, an error message is given. For demod_64:
> `Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/ActionHandler.py", line 348, in _handle_action self.get_flow_graph().update() File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/FlowGraph.py", line 403, in update self.create_labels() File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Element.py", line 78, in create_labels for child in self.get_children():child.create_labels() File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Block.py", line 212, in create_labels markups = [param.get_markup() for param in self.get_params() if param.get_hide() not in ('all', 'part')] File "/usr/lib/python2.7/dist-packages/gnuradio/grc/python/Param.py", line 170, in get_hide lambda p: ' '.join([p._type, p._nports]), self.get_parent().get_ports()) File "/usr/lib/python2.7/dist-packages/gnuradio/grc/python/Param.py", line 170, in <lambda> lambda p: ' '.join([p._type, p._nports]), self.get_parent().get_ports()) TypeError: sequence item 0: expected string, instance found Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/DrawingArea.py", line 150, in _handle_window_expose self._flow_graph.draw(gc, self._pixmap) File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/FlowGraph.py", line 372, in draw element.draw(gc, window) File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Block.py", line 318, in draw window.draw_drawable(gc, self.horizontal_label, 0, 0, x+BLOCK_LABEL_PADDING, y+(self.H-self.label_height)/2, -1, -1) AttributeError: 'Block' object has no attribute 'horizontal_label'`
> 
> For demod_8:
> 
> `Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/ActionHandler.py", line 348, in _handle_action self.get_flow_graph().update() File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/FlowGraph.py", line 403, in update self.create_labels() File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Element.py", line 78, in create_labels for child in self.get_children():child.create_labels() File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Block.py", line 212, in create_labels markups = [param.get_markup() for param in self.get_params() if param.get_hide() not in ('all', 'part')] File "/usr/lib/python2.7/dist-packages/gnuradio/grc/python/Param.py", line 170, in get_hide lambda p: ' '.join([p._type, p._nports]), self.get_parent().get_ports()) File "/usr/lib/python2.7/dist-packages/gnuradio/grc/python/Param.py", line 170, in <lambda> lambda p: ' '.join([p._type, p._nports]), self.get_parent().get_ports()) TypeError: sequence item 0: expected string, instance found Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/DrawingArea.py", line 150, in _handle_window_expose self._flow_graph.draw(gc, self._pixmap) File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/FlowGraph.py", line 372, in draw element.draw(gc, window) File "/usr/lib/python2.7/dist-packages/gnuradio/grc/gui/Block.py", line 318, in draw window.draw_drawable(gc, self.horizontal_label, 0, 0, x+BLOCK_LABEL_PADDING, y+(self.H-self.label_height)/2, -1, -1) AttributeError: 'Block' object has no attribute 'horizontal_label'`
> 
> EOF
I have same problem :(
Can you fix it ?
